name: 'LondonCrime'
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.13
    - pip
    - ipykernel
    - nb_conda_kernels
    - altair-all=5.5.*
    - vega_datasets
    - scipy
    - pip:
        - altair_ally