name: 'LondonCrime'
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.11
    - pip
    - ipykernel
    - nb_conda_kernels
    - altair-all=5.4.*
    - vega_datasets
    - scipy
    - shiny
    - pip:
        - altair_ally